name: nalelu
description: A new Flutter project.
publish_to: 'none'
version: 1.0.5+1.0.5

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  localization: ^2.1.0

  cupertino_icons: ^1.0.2
  provider: ^5.0.0

  # Location > Approximate location
  # App activity > App interactions
  # App info and performance > Crash logs, Diagnostics
  # Device or other identifiers > Device or other identifiers

  # Is this data collected, shared, or both? Shared
  # Is this data processed ephemerally? No
  # Is this data required for your app, or can users choose whether it’s collected? Data collection is required (users can’t turn off this data collection)
  # Why is this user data shared? Advertising or marketing
  google_mobile_ads: ^1.3.0

  nrs_flutter_lib:
    path: ../nrs-flutter-lib
  shared_preferences: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # flutter pub run flutter_launcher_icons:main
  flutter_launcher_icons: '^0.8.0'
  flutter_native_splash: ^0.2.8

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/banners/
    - assets/manga/
    - lib/i18n/

flutter_intl:
  enabled: true

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: true
  ios: true
  image_path_android: assets/icon.png
  image_path_ios: assets/icon.png
  adaptive_icon_background: assets/icon.png
  adaptive_icon_foreground: assets/icon.png

# flutter clean && flutter pub get && flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: '#ff2f00'
  image: assets/splash.png
  color_dark: '#ff2f00'
  android: true
  ios: true

  # Commands:
  # Build deployable IOS:         flutter build ipa
  # Build deployable Android:     flutter build appbundle
  # Build debug installable IOS:  flutter build ios
  # Install on phone:             flutter install
